define([], function () {

    var CaseInfo = {
        contentCard: function contentCard(data, type, idx) {
            var active = arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : false;
            var otherAttributes = arguments.length > 4 && arguments[4] !== undefined ? arguments[4] : false;

            var otherAttributesHtml = '\n                                        <div class="otherAttributtesCtnClsCm">\n                                            <div class="attributteCtnClsCm">\n                                                <label for="resolutionTypeName">Tipo Doc. Sustento:</label>\n                                                <input type="text" id="resolutionTypeName" name="resolutionTypeName" value="' + (data.resolutionTypeName || '---') + '" readonly>\n                                            </div>\n                                            <div class="attributteCtnClsCm">\n                                                <label for="resolutionDocument">Nro. Doc. Sustento:</label>\n                                                <input type="text" id="resolutionDocument" name="resolutionDocument" value="' + (data.resolutionDocument || '---') + '" readonly>\n                                            </div>\n                                        </div>   \n                                        <div class="otherAttributtesCtnClsCm">\n                                            <div class="attributteCtnClsCm">\n                                                <label for="floor">Piso:</label>\n                                                <input type="text" id="floor" name="floor" value="' + (data.floor || '---') + '" readonly>\n                                            </div>\n                                            <div class="attributteCtnClsCm">\n                                                <label for="municipalNumber">N\xFAmero municipal:</label>\n                                                <input type="text" id="municipalNumber" name="municipalNumber" value="' + (data.municipalNumber || '---') + '" readonly>\n                                            </div>\n                                        </div>                                     \n                                        ';
            var cardHtml = '<div class="caseInfoClsCm">\n                                <div class="headPredInfoClsCm ' + (type === 'original' ? 'headPredInfoOriginalClsCm' : 'headPredInfoResultClsCm') + '">\n                                    <span class="alignVCenter">Predio: ' + (data.cup || idx) + '</span>\n                                    <button class="zoomPredInfoClsCm ' + (type === 'original' ? 'active' : null) + ' toolsPredInfoClsCm" data-cup=' + data.cup + '>\n                                        <i class="fa fa-search" style="width: 16px; height: 16px"></i>\n                                    </button>\n                                    <button class="colapsePredInfoClsCm toolsPredInfoClsCm">\n                                        <i class=\'fas fa-angle-down\' style="width: 16px; height: 16px"></i>\n                                    </button>\n                                </div>\n                                <div class="bodyPredInfoClsCm ' + (active ? 'active' : null) + '">\n                                    <label for="direccion">Direcci\xF3n:</label>\n                                    <input type="text" id="direccion" name="direccion" value="' + data.address.replace("None", '') + '" readonly>\n                                    ' + (otherAttributes ? otherAttributesHtml : '') + '\n                                </div>\n                            </div>';
            return cardHtml;
        }
        // Otras funciones o propiedades
    };

    return CaseInfo;
});
//# sourceMappingURL=CaseInfo.js.map
